import useAuth from '@/hooks/useAuth'
import Head from 'next/head'
import useSWR from 'swr'
import axios from 'axios'

export default function Home() {
  const { user } = useAuth()
  const { data: rides, error, mutate } = useSWR(user ? '/api/rides' : null)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-4">
        {rides && !error ? (
          <div>
            {rides.map((ride, i) => (
              <article key={i}>
                <p>{ride.name}</p>
              </article>
            ))}
            <button
              type="button"
              className="mt-3 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              onClick={() => {
                axios
                  .post('/api/rides', { name: 'Test ride', date: new Date() })
                  .then(res => console.log(res))
                  .catch(err => console.error(err))
                  .finally(() => mutate())
              }}
            >
              Add ride
            </button>
          </div>
        ) : null}
      </main>
    </>
  )
}
