import Head from 'next/head'
import useSWR from 'swr'
import axios from 'axios'

export default function Home() {
  const { data, error } = useSWR('/api/rides/123456')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-4">
        {data && !error ? <p>{data.id}</p> : null}
        <button
          type="button"
          className="mt-3 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
          onClick={() => {
            axios
              .post('/api/rides', { name: 'Test ride', date: new Date() })
              .then(res => console.log(res))
          }}
        >
          Add ride
        </button>
      </main>
    </>
  )
}
